version: '3.7'

services:
  liquibase-migrations:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: liquibase-migrations
    env_file:
      - .env
    volumes:
      - ./migrations:${MIGRATIONS_PATH:-/opt/migrations}
    command:
      - '--classpath=/liquibase/changelog'
      - '--url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}'
      - '--username=${DATABASE_USER}'
      - '--password=${DATABASE_PASS}'
      - '--changeLogFile=./master.yaml'
      - 'update'
    external_links:
      - postgres
    networks:
      internal:

networks:
  internal:
    name: local
    external: true